#
# Copyright (c) 2026 Huawei Technologies Co., Ltd. All Rights Reserved.
# This file is a part of the vllm-ascend project.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
#

from .dequant import (
    build_token_map_from_block_table,
    custom_dequant_enabled,
    debug_compare_enabled,
    fused_attention_custom_enabled,
    k_score_custom_enabled,
    prod_custom_dequant_enabled,
    tq_prod_mse_paged_attention,
    tq_prod_mse_paged_attention_reference,
    tq_dequant_mse_paged_reference_rot,
    tq_dequant_mse_paged_rot,
    tq_dequant_mse_paged_scaled_rot,
    tq_dequant_prod_paged_k_score,
    tq_dequant_prod_paged_k_score_reference,
    tq_dequant_prod_paged_reference_rot,
    tq_dequant_prod_paged_rot,
)
from .fused import (
    combined_kv_mse_encode_enabled,
    compressed_decode_current_custom_k_score_enabled,
    compressed_decode_current_enabled,
    current_lengths_from_start_loc,
    decode_compressed_full_cache_enabled,
    encode_cache_update_custom_enabled,
    encode_cache_update_force_fp32_input,
    encode_cache_update_stage_profile_enabled,
    encode_cache_update_structured_fast_enabled,
    encode_cache_update_v_partitions,
    fused_decode_attention_m4_enabled,
    fused_kv_update_attention_custom_enabled,
    fused_kv_update_attention_enabled,
    old_seq_lens_from_total,
    tq_decode_history_to_dense,
    tq_encode_kv_to_paged_cache,
    tq_encode_kv_to_paged_cache_reference,
    tq_fused_kv_update_attention,
    tq_fused_kv_update_attention_reference,
    tq_fused_decode_history_current_attention,
    tq_prod_mse_history_current_decode_attention,
)

__all__ = [
    "build_token_map_from_block_table",
    "custom_dequant_enabled",
    "debug_compare_enabled",
    "fused_attention_custom_enabled",
    "k_score_custom_enabled",
    "prod_custom_dequant_enabled",
    "tq_prod_mse_paged_attention",
    "tq_prod_mse_paged_attention_reference",
    "tq_dequant_mse_paged_reference_rot",
    "tq_dequant_mse_paged_rot",
    "tq_dequant_mse_paged_scaled_rot",
    "tq_dequant_prod_paged_k_score",
    "tq_dequant_prod_paged_k_score_reference",
    "tq_dequant_prod_paged_reference_rot",
    "tq_dequant_prod_paged_rot",
    "combined_kv_mse_encode_enabled",
    "compressed_decode_current_custom_k_score_enabled",
    "compressed_decode_current_enabled",
    "current_lengths_from_start_loc",
    "decode_compressed_full_cache_enabled",
    "encode_cache_update_custom_enabled",
    "encode_cache_update_force_fp32_input",
    "encode_cache_update_stage_profile_enabled",
    "encode_cache_update_structured_fast_enabled",
    "encode_cache_update_v_partitions",
    "fused_decode_attention_m4_enabled",
    "fused_kv_update_attention_custom_enabled",
    "fused_kv_update_attention_enabled",
    "old_seq_lens_from_total",
    "tq_decode_history_to_dense",
    "tq_encode_kv_to_paged_cache",
    "tq_encode_kv_to_paged_cache_reference",
    "tq_fused_kv_update_attention",
    "tq_fused_kv_update_attention_reference",
    "tq_fused_decode_history_current_attention",
    "tq_prod_mse_history_current_decode_attention",
]
